apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-nginx-ingress
  namespace: demo-ingress ## previous namespace name
spec:
  ingressClassName: nginx
  rules:
  - host: praveen.buzz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-svc ##previous service name
            port:
              number: 80

### all information you provided is correct ingress will create the dns address you can host that address in rooute 53 
               

